name: validate
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        go_version:
          - 1.23
          - 1.24
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go_version }}.x"
          cache: false # golangci-lint-action does its own caching
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.59.1
          args: --timeout=3m
